### ISSUE TITLE
Apply Spotify theme not working on Fedora(26) - gksu not found

### ISSUE THREAD

**Issue by ariSunz** [actionless/oomox#93]
The process appears to go on as usual (specifying "/usr/lib/spotify-client/Apps/" as the target directory in Fedora, if you install through the negativo17 repo), until this pops up:
`/opt/oomox/oomox_gui/../oomoxify.sh: line 268: gksu: command not found`

gksu is not present in Fedora (it is replaced by beesu), so I guess the script doesn't look for an alternative?

Using oomoxify-cli with sudo does work.

**Comment by actionless** [comment]
i think just looking for beesu instead of gksu will be not enough for Wayland users (which seems to be by default in Fedora now):
https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Graphical_applications_can.27t_be_run_as_root_from_terminal

so i'll look into rewriting that part using `polkit`
